CREATE TABLE IF NOT EXISTS files (
    "ID" UUID PRIMARY KEY DEFAULT gen_random_uuid (),
    "userID" UUID,
    "name" VARCHAR(150) UNIQUE NOT NULL,
    "path" VARCHAR(255) UNIQUE NOT NULL,
    "size" INTEGER NOT NULL,
    "mimeType" VARCHAR(30) NOT NULL,
    "createdAtUTC" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    "updatedAtUTC" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_userID FOREIGN KEY ("userID") REFERENCES users ("ID")
);

CREATE INDEX IF NOT EXISTS idx_file_name ON files ("name");