CREATE TABLE IF NOT EXISTS users (
    "ID" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(100) NOT NULL,
    email VARCHAR(254) UNIQUE NOT NULL,
    "password" VARCHAR(255) NOT NULL,
    phone VARCHAR(10) UNIQUE NOT NULL,
    "createdAtUTC" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    "updatedAtUTC" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_users_email ON users (email);
